# Use devopsdockeruh/simple-web-service:alpine as the base image
FROM devopsdockeruh/simple-web-service:alpine

# Set the command to run the server automatically when the container starts
CMD ["server"]
